sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "DpfBfOwMPJXs7TnrnRej7WGPwQ782hXAOiryXF3gjbug/GOfRVZkY4296EExTOr4GRCFnrW6ALQy5ED12/tzrjr40J1l+JAgo7KPYAWDp8ZPqOed0oxBF9V9Xnj0HnlPWqqvtp4nir0hV/LgjQxevO6oSTzXwUfr/JftAnPcAIw="
  on:
    tags: true
    all_branches: true
